Phoenix
    Leviathan
        Golem
            Sylph
                Salamander
                    Ifrit
                        Pyreclaw
                            Kraken
                                Tidalon
                                    Nautilus
                                        Terrafin
                                            Quakebeast
                                                Duramole
                                                    Zephyrwing
                                                        Stratus
                                                            Cloudweaver
                                                                Mechadillo
                                                                    Chronitron
                                                                        Circuitros
                                                                            Tekknight
                                                                                Cultling
                                                                                    Nyarlapup
                                                                                        Shogghorn
                                                                                            Azatheon
                                                                                                Hellhound
                                                                                                    Infernalimp
                                                                                                        Malgarg
                                                                                                            Souldevourer
                                                                                                                Angelion
                                                                                                                    Serapion
                                                                                                                        Radiantis
                                                                                                                            Sanctidrae
                                                                                                                                Staticork
                                                                                                                                    Stormbather
                                                                                                                                        Ampbeetle
                                                                                                                                            Thunderpole
                                                                                                                                                Drakenroost
                                                                                                                                                    Wyrmling
                                                                                                                                                        Basilisk
                                                                                                                                                            Wyvern
                                                                                                                                                                Mindraker
                                                                                                                                                                    Astromoth
                                                                                                                                                                        Telephant
                                                                                                                                                                            Clairvoxa
                                                                                                                                                                                Pumafist
                                                                                                                                                                                    Fistape
                                                                                                                                                                                        Brawligator
                                                                                                                                                                                            Thundermonk
                                                                                                                                                                                                Mushape
                                                                                                                                                                                                    Armaduff
                                                                                                                                                                                                        Kangaroost
                                                                                                                                                                                                            Equinix

                                                                                                                                                                                                                Tidalon
                                                                                                                                                                                                                    Nautilus
                                                                                                                                                                                                                        Terrafin
                                                                                                                                                                                                                            Quakebeast
                                                                                                                                                                                                                                Duramole
                                                                                                                                                                                                                                    Stratus
                                                                                                                                                                                                                                        Cloudweaver
                                                                                                                                                                                                                                            Mechadillo
                                                                                                                                                                                                                                                Chronitron
                                                                                                                                                                                                                                                    Circuitros
                                                                                                                                                                                                                                                        Tekknight
                                                                                                                                                                                                                                                            Cultling
                                                                                                                                                                                                                                                                Nyarlapup
                                                                                                                                                                                                                                                                    Shogghorn

                                                                                                                                                                                                                                                                        Hellhound
                                                                                                                                                                                                                                                                            Infernalimp
                                                                                                                                                                                                                                                                                Malgarg
                                                                                                                                                                                                                                                                                    Souldevourer
                                                                                                                                                                                                                                                                                        Angelion
                                                                                                                                                                                                                                                                                            Serapion
                                                                                                                                                                                                                                                                                                Radiantis
                                                                                                                                                                                                                                                                                                    Sanctidrae
                                                                                                                                                                                                                                                                                                        Staticork
                                                                                                                                                                                                                                                                                                            Stormbather
                                                                                                                                                                                                                                                                                                                Ampbeetle
                                                                                                                                                                                                                                                                                                                    Thunderpole
                                                                                                                                                                                                                                                                                                                        Drakenroost
                                                                                                                                                                                                                                                                                                                            Wyrmling
                                                                                                                                                                                                                                                                                                                                Basilisk
                                                                                                                                                                                                                                                                                                                                    Wyvern
                                                                                                                                                                                                                                                                                                                                        Mindraker
                                                                                                                                                                                                                                                                                                                                            Astromoth
                                                                                                                                                                                                                                                                                                                                                Telephant
                                                                                                                                                                                                                                                                                                                                                    Clairvoxa
                                                                                                                                                                                                                                                                                                                                                        Pumafist
                                                                                                                                                                                                                                                                                                                                                            Fistape
                                                                                                                                                                                                                                                                                                                                                                Brawligator
                                                                                                                                                                                                                                                                                                                                                                    Thundermonk
                                                                                                                                                                                                                                                                                                                                                                        Mushape
                                                                                                                                                                                                                                                                                                                                                                            Armaduff
                                                                                                                                                                                                                                                                                                                                                                                Kangaroost Equinix