#include <SFML/Graphics.hpp>
#include <iostream>
#include "map.h"
#include "render.h"
#include "tile.h"
#include "colors.h"
#include "engine.h"
#include "player.h"
#include "input.h"
#include "monster.h"

Tile level1[24][16] = {
    {
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile('"', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile(' ', Color::BLUE, true),
        Tile('#', Color::BLUE, false),
    },
    {
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
        Tile('#', Color::BLUE, false),
    }};

int main()
{
    sf::RenderWindow window(sf::VideoMode(1200, 800), "");
    Render render;
    Map map;
    Engine engine;
    Player player;
    InputManager inputManager;
    MonsterManager monsterManager;
    Environment environment;

    // Initialize monster types before creating any monsters
    monsterManager.initializeMoveTypes();
    monsterManager.initializeMonsterTypes();
    render.selection = 0;
    render.loadFont();

    memcpy(map.currentMap, level1, sizeof(level1));
    bool needsUpdate = true;

    // Initialize player position
    player.setPosition(5, 5);

    // Set initial options based on game state
    engine.setState(GAME_MAIN_MENU, player);
    std::cout << "Menu size: " << engine.menuOptions.size() << std::endl;
    for (int i = 0; i < engine.menuOptions.size(); i++)
    {
        std::string option = engine.menuOptions[i];
    }

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();

            if (event.type == sf::Event::KeyPressed)
            {
                needsUpdate = inputManager.handleInput(event, player, monsterManager, map, engine, render.selection);
            }
        }

        if (needsUpdate)
        {
            window.clear();
            engine.update(map, player, environment, monsterManager);
            render.drawScreen(window, engine, map, player, monsterManager, environment, render.selection);
            window.display();
            needsUpdate = false;
        }
    }

    return 0;
}